/****** v1 | Description: Customer information class  | 12/13/2017 | L OMeara */
public class CustomerWrapper {
    public ID customerID{get;set;}
    public String globalID{get;set;}
    public String firstName{get;set;}
    public String lastName{get;set;}
    public String email{get;set;}
    public String email2{get;set;}
    public String phone{get;set;}
    public String phone2{get;set;}
    public String phone3{get;set;}
    public String primaryLanguage{get;set;}
    public Boolean taxExempt{get;set;}
    public Boolean seeManagement{get;set;}
    public String twitterId{get;set;}
    public String facebookId{get;set;}
    public String instagramId{get;set;}
    public String snapchatId{get;set;}
    public String youTubeId{get;set;}
    public String pinterestId{get;set;}
    public String addressLine1{get;set;}
    public String addressLine2{get;set;}
    public String city{get;set;}
    public String state{get;set;}
    public String zip{get;set;}
    public String country{get;set;}
    public Date customerSince{get;set;}
}