public class POJSON{
		public ExtDetail ExtDetail{get;set;}
	public class ExtDetail{
		public String Street{get;set;}
		public String Address3{get;set;}
		public String Address2{get;set;}
		public String ZipCode{get;set;}
		public String Address1{get;set;}
		public String ShipDate{get;set;}
		public String PONumber{get;set;}
		public String UPSTracking{get;set;}
		public String ShipTo{get;set;}
		public String DefectCode{get;set;}
		public String Customer{get;set;}
		public String DefectLocation{get;set;}
		public String ShipVia{get;set;}
		public String Model{get;set;}
		public String RPKey{get;set;}
	}
}