public class TresholdEnabledWrapper {
    
    
    @AuraEnabled
    public integer DefaultValue {get;set;}
    
    @AuraEnabled
    public String Name {get;set;}
    
    @AuraEnabled    
    public integer ProfitCenter {get;set;}
    
    @AuraEnabled    
    public String SubProfitCenter {get;set;}    
    
    @AuraEnabled    
    public integer PropertyGroup {get;set;}
    
    @AuraEnabled    
    public integer Value {get;set;}  
}